name: Project Sync

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  add-to-project:
    uses: ./.github/workflows/reusable/project-sync.yml
    with:
      project-url: https://github.com/users/blackboxprogramming/projects/8
    permissions:
      contents: read
      pull-requests: write
      issues: write
